config/routes.rb
Rails.application.routes.draw do
  root 'front#index'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  resources :users, only: [:new, :create]
  resources :tasks, only: [:index, :create, :update, :edit]
  resources :task_lists, except: [:index, :show] do
    resources :tasks, only: [:new]
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:update]
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  validates :title, presence: { message: 'required. '}
  validate :no_past_dates, on: :create
  validate :linear_time
  has_attached_file :attachment,
                    storage: :s3
  validates_attachment_file_name :attachment, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/, /pdf\Z/]
  scope :present, -> { where('start < ?', Date.today+1) }
  scope :incomplete, -> { where(status: false) }

  def complete?
    status
  end

  def display_complete
    status ? 'Completed!' : 'Incomplete'
  end

  def friendly_start_date
    start < Date.today ? 'Began on ' + start.to_s : 'Begins on ' + start.to_s
  end

  def future?
    start > Date.today
  end

  private

  def no_past_dates
    errors.add(:start, "can't be in the past. ") if start < Date.today
    errors.add(:due, "can't be in the past. ") if due < Date.today
  end

  def linear_time
    errors.add(:due, "can't be before the start date. ") if due < start
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: { message: 'required. ' }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :task_lists
  validates :email, presence: { message: 'required. ' },
                    uniqueness: { message: 'already in use. '}
  validates :password, presence: { message: 'required. '},
                       confirmation: { message: 'must match confirmation. '}
  validates :password_confirmation, presence: { message: 'required. '}
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
  respond_to :json

  def update
    respond_with Task.find(params[:id]).update(task_params)
  end

  private

  def task_params
    params.require(:task).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_cookie
    redirect_to tasks_path if cookies.signed[:session]
  end

  def current_user
    User.find(cookies.signed[:session])
  end

  def any_user
    unless cookies.signed[:session]
      flash[:red] = "You need to be logged in!"
      redirect_to root_path
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  before_action :check_cookie

  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      cookies.signed[:session] = { value: user.id, expires: Time.now + 3600 }
      redirect_to tasks_path
    else
      flash[:red] = "Check your credentials."
      redirect_to :back
    end
  end

  def destroy
    cookies.delete(:session)
    redirect_to root_path
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :any_user

  def new
    @task_list = TaskList.new()
  end

  def create
    list = current_user.task_lists.new(task_list_params)
    if list.valid?
      list.save
      redirect_to tasks_path
    else
      flash[:red] = "Couldn't be done."
      list.errors.full_messages.each do |message|
        flash[:red] << message
      end
      redirect_to :back
    end
  end

  def edit
    @task_list = TaskList.find(params[:id])
    unless @task_list.user == current_user
      flash[:red] = "That's not yours!"
      redirect_to tasks_path
    end
  end

  def update
    list = TaskList.new(task_list_params)
    if list.valid?
      TaskList.find(params[:id]).update(task_list_params)
      redirect_to tasks_path
    else
      flash[:red] = "Couldn't be done."
      list.errors.full_messages.each do |message|
        flash[:red] << message
      end
      redirect_to :back
    end
  end

  def destroy
    list = TaskList.find(params[:id])
    unless list.user == current_user
      flash[:red] = "That's not yours!"
      redirect_to tasks_path
    end
    list.destroy
    redirect_to tasks_path
  end

  private

  def task_list_params
    params.require(:task_list).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :any_user

  def index
    @user = User.includes(:task_lists).find(cookies.signed[:session])
  end

  def new
    @task = TaskList.find(params[:task_list_id]).tasks.new()
  end

  def create
    task = Task.create(task_params)
    if task.valid?
      task.save
      redirect_to tasks_path
    else
      flash[:red] = "Couldn't be done."
      task.errors.full_messages.each do |message|
        flash[:red] << message
      end
      redirect_to :back
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.new(task_params)
    if task.valid?
      Task.find(params[:id]).update(task_params)
      redirect_to tasks_path
    else
      flash[:red] = "Couldn't be done."
      task.errors.full_messages.each do |message|
        flash[:red] << message
      end
      redirect_to :back
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :notes, :start, :due, :task_list_id, :attachment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.valid?
      cookies.signed[:session] = { value: user.id, expires: Time.now + 3600 }
      redirect_to tasks_path
    else
      flash[:red] = "Sorry, but... "
      user.errors.full_messages.each do |message|
        flash[:red] << message
      end
      redirect_to :back
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/api/v1/tasks_helper.rb
module Api::V1::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/front/index.html.erb
<%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hyperlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tinysort/2.2.2/tinysort.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

	<h1>🅷🅈🄿🄴🅁🄻🄸🅂🅃</h1>

	<% flash.each do |key, message| %>
		<div class="flash-<%= key %>"><%= message %></div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/task_lists/edit.html.erb
<h2>Edit Task List</h2>

<%= form_for @task_list do |f| %>
	<%= f.label :title, "Title:" %>
	<%= f.text_field :title %><br>
	<%= f.label :description, "Description:" %>
	<%= f.text_area :description %><br>
	<%= f.submit "Change" %>
<% end %>

app/views/task_lists/new.html.erb
<h2>New Task List</h2>

<%= form_for @task_list do |f| %>
	<%= f.label :title, "Title:" %>
	<%= f.text_field :title %><br>
	<%= f.label :description, "Description:" %>
	<%= f.text_area :description %><br>
	<%= f.submit "Create" %>
<% end %>

app/views/tasks/_filter.html.erb
<label>Filter tasks in this list by title:</label> <input type="text" class="filter-name"></input> 
<label>Filter tasks in this list by status:</label> <%= select :task, :filter_status, ['incomplete', 'complete', 'all'], {include_blank: false} %> 
<br><button class="sort-title">Sort Tasks by Title</button> 
<button class="sort-status">Sort Tasks by Status</button> 
<button class="sort-due">Sort Tasks by Due Date</button>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_for @task, multipart: true do |f| %>
	<%= f.label :title, "Title:" %>
	<%= f.text_field :title %><br>
	<%= f.label :start, "Starts on:" %>
	<%= f.date_select :start %><br>
	<%= f.label :due, "Due on:" %>
	<%= f.date_select :due %><br>
	<%= f.label :notes, "Notes:" %>
	<%= f.text_area :notes %><br>
	<%= f.label :attachment, "Attach a file:" %>
	<%= f.file_field :attachment %><br>
	<%= f.submit "Change" %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to 'Log Out', logout_path %><br>

<%= link_to 'New Task List', new_task_list_path %>

<% @user.task_lists.each do |list| %>
	<div class="task-list" data-id="<%= list.id %>">
		<h3><%= list.title %></h3><%= link_to 'Change Details', edit_task_list_path(list)	 %> <%= link_to 'Remove List', task_list_path(list), method: :delete %><br>
		<div class="task-holder">
			<label>Filter tasks in this list by due date:</label><%= select :task, :filter_due, list.tasks.pluck(:due).uniq, {include_blank: true} %>
			<label>Filter tasks in this list by starting date:</label><%= select :task, :filter_start, list.tasks.pluck(:start).uniq, {include_blank: true} %><br>
			<%= render partial: 'filter' %>
			<% list.tasks.each do |task| %>
				<div class="task <%= 'hide' if task.complete? || task.future? %>" data-id="<%= task.id %>" data-status='<%= task.complete? %>' data-due="<%= task.due %>">
					<h4 class="task-title"><%= task.title %></h4>
					<span class="status"><%= task.display_complete %></span> <button class="task-status">Toggle Status</button>
					<p class="begin"><%= task.friendly_start_date %></p>
					<p class="due">Due on <%= task.due %></p>
					<p class="notes"><%= task.notes %></p>
					<% if task.attachment_file_name %>
						Attached file: <%= link_to task.attachment.url, task.attachment.url %>
					<% end %>
					<%= link_to 'Change Task Details', edit_task_path(task) %>
				</div>
			<% end %>
		</div>
		<br><button class="show-all">Show All Tasks</button>
		<br><%= link_to 'Add Task', new_task_list_task_path(list) %>
	</div>
<% end %>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_for @task, multipart: true do |f| %>
	<%= f.label :title, "Title:" %>
	<%= f.text_field :title %><br>
	<%= f.label :start, "Starts on:" %>
	<%= f.date_select :start %><br>
	<%= f.label :due, "Due on:" %>
	<%= f.date_select :due %><br>
	<%= f.label :notes, "Notes:" %>
	<%= f.text_area :notes %><br>
	<%= f.label :attachment, "Attach a file:" %>
	<%= f.file_field :attachment %><br>
	<%= f.hidden_field :task_list_id, value: params[:task_list_id] %>
	<%= f.submit "Create" %>
<% end %>

app/views/users/new.html.erb
<h2>Register New User</h2>

<%= form_for @user do |f| %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name %><br>
	<%= f.label :email, "Email:" %>
	<%= f.text_field :email %><br>
	<%= f.label :password, "Password:" %>
	<%= f.password_field :password %><br>
	<%= f.label :password_confirmation, "Confirm Password:" %>
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Finish" %>
<% end %>

Or <%= link_to "log in as an existing user", login_path %>